// <auto-generated />
using System;
using Invengo.Library.MIS.EntityFrameworkCore.RFID;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Invengo.Library.MIS.Migrations.RFIDMigrationsDb
{
    [DbContext(typeof(RFIDMigrationsDbContext))]
    partial class RFIDMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Invengo.Library.MIS.RFID.BookInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("szBookID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("bBookLabelChecked")
                        .HasColumnType("bit");

                    b.Property<bool?>("bForceSortCase")
                        .HasColumnType("bit");

                    b.Property<int?>("bLostBookFlag")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dtAutoUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtBorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtConvertDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtLastRead")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtNeedBackDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtPublishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("fPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("nBookLenType")
                        .HasColumnType("int");

                    b.Property<int?>("nBookStatus")
                        .HasColumnType("int");

                    b.Property<int?>("nBookThickness")
                        .HasColumnType("int");

                    b.Property<int?>("nBooksTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("nConvertStaffID")
                        .HasColumnType("int");

                    b.Property<long?>("nEPCOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("nLabelID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nPages")
                        .HasColumnType("int");

                    b.Property<int?>("nPublishID")
                        .HasColumnType("int");

                    b.Property<int?>("nRenewTime")
                        .HasColumnType("int");

                    b.Property<int?>("nSetInfoCount")
                        .HasColumnType("int");

                    b.Property<int?>("nSetInfoOrder")
                        .HasColumnType("int");

                    b.Property<int?>("nStaffID")
                        .HasColumnType("int");

                    b.Property<int?>("nStartYear")
                        .HasColumnType("int");

                    b.Property<int?>("nUpdateStaffID")
                        .HasColumnType("int");

                    b.Property<string>("szAuthor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szBookCaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szBookIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szBookLen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szBookSSID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szCardID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szClassNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szConvertStaff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMainWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMedicalLib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMemo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMoneyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szPretendIndexNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szPublishyear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szSeriesID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szTemplibCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szlibCD")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookInfo");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.BorrowHisIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nHisIndexID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dtOperateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nFailCount")
                        .HasColumnType("int");

                    b.Property<int?>("nGlideIndex")
                        .HasColumnType("int");

                    b.Property<int?>("nOperateType")
                        .HasColumnType("int");

                    b.Property<int?>("nStaffID")
                        .HasColumnType("int");

                    b.Property<int?>("nSucCount")
                        .HasColumnType("int");

                    b.Property<string>("szGlideID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szIPAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szInterLendLib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szInterLendNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMacAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szReaderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szReaderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szReaderPwd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BorrowHisIndex");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.BorrowHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nHistoryID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bBooking")
                        .HasColumnType("bit");

                    b.Property<bool?>("bResult")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dtNeedBack")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nBooksTypeID")
                        .HasColumnType("int");

                    b.Property<short?>("nHavePrint")
                        .HasColumnType("smallint");

                    b.Property<int?>("nHisIndexID")
                        .HasColumnType("int");

                    b.Property<string>("szBookID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szBookIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szBookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szBooksType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szCardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szCheckInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szLibCDByType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMemo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szReaderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szReaderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BorrowHistory");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.CRD_TRANS_Recd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("bAddReaderRsult")
                        .HasColumnType("bit");

                    b.Property<bool?>("bError")
                        .HasColumnType("bit");

                    b.Property<bool?>("bReBackCard")
                        .HasColumnType("bit");

                    b.Property<bool?>("bSendCard")
                        .HasColumnType("bit");

                    b.Property<bool>("bSettleAccounts")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dtSendCard")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtSettleAccounts")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtTransBegin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtTransDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("fDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("fNeedDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nCardID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nCardTypeID")
                        .HasColumnType("int");

                    b.Property<short>("nOperateType")
                        .HasColumnType("smallint");

                    b.Property<short>("nRecordStep")
                        .HasColumnType("smallint");

                    b.Property<string>("szCardDevice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szDeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szIdentifyCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szOperateDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szReaderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szStaffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szStep")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CRD_TRANS_Recd");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nCardTypeID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ValidDay")
                        .HasColumnType("int");

                    b.Property<string>("beginTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dtAddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("endTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("fDeposit")
                        .HasColumnType("float");

                    b.Property<int?>("nLevel")
                        .HasColumnType("int");

                    b.Property<int?>("nStaffID")
                        .HasColumnType("int");

                    b.Property<string>("szCardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szILSTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szStaffName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CardType");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.DeviceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nDeviceID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("bAutoSaveVideo")
                        .HasColumnType("bit");

                    b.Property<bool?>("bCanPing")
                        .HasColumnType("bit");

                    b.Property<bool>("bIsValid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dtUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("nBuildingNo")
                        .HasColumnType("int");

                    b.Property<int>("nFloorNo")
                        .HasColumnType("int");

                    b.Property<int>("nRoomNo")
                        .HasColumnType("int");

                    b.Property<int?>("nStaffID")
                        .HasColumnType("int");

                    b.Property<int?>("nSubSystemID")
                        .HasColumnType("int");

                    b.Property<int?>("nTypeNo")
                        .HasColumnType("int");

                    b.Property<int>("nVideoChannel1")
                        .HasColumnType("int");

                    b.Property<int>("nVideoChannel2")
                        .HasColumnType("int");

                    b.Property<int>("nVideoChannel3")
                        .HasColumnType("int");

                    b.Property<int>("nVideoChannel4")
                        .HasColumnType("int");

                    b.Property<int>("nVideoNum")
                        .HasColumnType("int");

                    b.Property<int>("nXCoordinate")
                        .HasColumnType("int");

                    b.Property<int>("nYCoordinate")
                        .HasColumnType("int");

                    b.Property<string>("szDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szDeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceInfo");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.JanitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nJanitorLogID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dtLogTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("lEPCOrder")
                        .HasColumnType("bigint");

                    b.Property<int?>("nBookStatus")
                        .HasColumnType("int");

                    b.Property<string>("szBookID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szBookIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szBookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szJanitorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JanitorLog");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("bForceSortCase")
                        .HasColumnType("bit");

                    b.Property<bool?>("bInitSortOver")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dtAddDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("nDefaultStatus")
                        .HasColumnType("int");

                    b.Property<int?>("nStaffID")
                        .HasColumnType("int");

                    b.Property<string>("szMedicalLib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szStaffName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.Reader", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("szReaderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("bSex")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dtBirthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtConvertDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtRegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtlapse")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("fBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("fDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("fOwe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("imgPic")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("nCardID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("nCardOrder")
                        .HasColumnType("smallint");

                    b.Property<int?>("nCardStatusID")
                        .HasColumnType("int");

                    b.Property<int?>("nCardTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("nConvertStaffID")
                        .HasColumnType("int");

                    b.Property<long?>("nEPCOrder")
                        .HasColumnType("bigint");

                    b.Property<int?>("nLibraryNo")
                        .HasColumnType("int");

                    b.Property<string>("szAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szCardPswd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szEduLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szFinger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMajorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMajorNameSub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szProRanks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szidentityCard")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reader");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.ReaderINOUTLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dtRecordTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("nCounter")
                        .HasColumnType("int");

                    b.Property<short?>("nType")
                        .HasColumnType("smallint");

                    b.Property<string>("szJanitorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szReaderID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReaderINOUTLog");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.VerifyIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("CardType")
                        .HasColumnType("smallint");

                    b.Property<string>("ReaderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerifyIdentityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dtRecordTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VerifyIdentity");
                });

            modelBuilder.Entity("Invengo.Library.MIS.RFID.duStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nStaffID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("bIsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("bIsValid")
                        .HasColumnType("bit");

                    b.Property<bool?>("bSex")
                        .HasColumnType("bit");

                    b.Property<int?>("nDeptID")
                        .HasColumnType("int");

                    b.Property<string>("szAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szEMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szFinger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("duStaff");
                });
#pragma warning restore 612, 618
        }
    }
}
